version: '3'
services:
  core:
    build:
      context: .
      dockerfile: Dockerfile.core
    container_name: core
    environment:
      - DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./src:/src
    privileged: true
    stdin_open: true 
    tty: true